# -*- coding: utf-8 -*-
"""rpg_queries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ufwd5h-epfNkHGiNJTkFTDQsbupk24Ld
"""

#How many total characters are there?
import sqlite3

conn = sqlite3.connect('rpg_db.sqlite3')
curs = conn.cursor()

#How many total characters are there?
query1 = "SELECT count(name) as character_count FROM charactercreator_character"

results1 = curs.execute(query1).fetchall()

print("Total number of characters=", results1)

#How many in each sublass?

#cleric subclass
query2= "SELECT count(character_ptr_id) as character_count FROM charactercreator_cleric"
results2 = curs.execute(query2).fetchall()

print("Total number of characters in cleric sublass=", results2)

#fighter sublass
query3 = "SELECT count(character_ptr_id) as character_count FROM charactercreator_fighter"
results3 = curs.execute(query3).fetchall()

print("Total number of characters in fighter sublass=", results3)

#mage sublass
query4 = "SELECT count(character_ptr_id) as character_count FROM charactercreator_mage"
results4 = curs.execute(query4).fetchall()

print("Total number of characters in mage sublass=", results4)

#thief sublass
query5 = "SELECT count(character_ptr_id) as character_count FROM charactercreator_thief"
results5 = curs.execute(query5).fetchall()

print("Total number of characters in thief sublass=", results5)

#necromancer is a sublass of mage, so we don't need to count it separately
#The sum of each individual class from the above is = 302, total number of characters

#extrating table with each character and its class
query6="""

SELECT 
  ch.character_id
  ,ch.name
  --,cl.*
  --,f.*
  --,m.*
  --,th.*
  -- ,if(cl.character_ptr_id is not null, "cleric", "todo") as char_type
  ,CASE 
  WHEN cl.character_ptr_id is not null THEN "cleric"
  WHEN f.character_ptr_id is not null THEN "fighter"
  WHEN n.mage_ptr_id is not null THEN "mage-necro"
  WHEN m.character_ptr_id is not null THEN "mage"
  WHEN th.character_ptr_id is not null THEN "thief"
  ELSE "todo"
  END as char_type
from charactercreator_character as ch
left join charactercreator_cleric as cl on ch.character_id = cl.character_ptr_id
left join charactercreator_fighter as f on ch.character_id = f.character_ptr_id
left join charactercreator_mage as m on ch.character_id = m.character_ptr_id
left join charactercreator_thief as th on ch.character_id = th.character_ptr_id
-- left join charactercreator_necromancer as n on ch.character_id = n.character_ptr_id
left join charactercreator_necromancer as n on m.character_ptr_id = n.mage_ptr_id
"""
curs.execute(query6).fetchall()

#Number of characters in each class

query7= """
select
  subquery1.char_type
  ,count(distinct subquery1.character_id) as char_count
from (
    -- row per character (302 total)
    select 
      ch.character_id
      ,ch.name
      --,cl.*
      --,f.*
      --,m.*
      --,th.*
      -- ,if(cl.character_ptr_id is not null, "cleric", "todo") as char_type
      ,CASE 
      WHEN cl.character_ptr_id is not null THEN "cleric"
      WHEN f.character_ptr_id is not null THEN "fighter"
      WHEN n.mage_ptr_id is not null THEN "mage-necro"
      WHEN m.character_ptr_id is not null THEN "mage"
      WHEN th.character_ptr_id is not null THEN "thief"
      ELSE "todo"
      END as char_type
    from charactercreator_character as ch
    left join charactercreator_cleric as cl on ch.character_id = cl.character_ptr_id
    left join charactercreator_fighter as f on ch.character_id = f.character_ptr_id
    left join charactercreator_mage as m on ch.character_id = m.character_ptr_id
    left join charactercreator_thief as th on ch.character_id = th.character_ptr_id
    -- left join charactercreator_necromancer as n on ch.character_id = n.character_ptr_id
    left join charactercreator_necromancer as n on m.character_ptr_id = n.mage_ptr_id
) subquery1
group by subquery1.char_type
"""
curs.execute(query7).fetchall()

#Another way to find number of characters in each class

query8= """
 
    -- row per character (302 total)
select 
  CASE 
  WHEN cl.character_ptr_id is not null THEN "cleric"
  WHEN f.character_ptr_id is not null THEN "fighter"
  WHEN n.mage_ptr_id is not null THEN "mage-necro"
  WHEN m.character_ptr_id is not null THEN "mage"
  WHEN th.character_ptr_id is not null THEN "thief"
  ELSE "todo"
  END as char_type
  ,count(distinct ch.character_id) as char_count
from charactercreator_character as ch
left join charactercreator_cleric as cl on ch.character_id = cl.character_ptr_id
left join charactercreator_fighter as f on ch.character_id = f.character_ptr_id
left join charactercreator_mage as m on ch.character_id = m.character_ptr_id
left join charactercreator_thief as th on ch.character_id = th.character_ptr_id
-- left join charactercreator_necromancer as n on ch.character_id = n.character_ptr_id
left join charactercreator_necromancer as n on m.character_ptr_id = n.mage_ptr_id
group by char_type
"""

curs.execute(query8).fetchall()

#How many total items?
query9= """
select count(name) as item_count
from armory_item
"""
results6 = curs.execute(query9).fetchall()

print("Total number of items=", results6)

#How many items each character has? 
query10="""

SELECT a.character_id, ch.name, count(a.item_id)
FROM charactercreator_character_inventory as a
left join charactercreator_character as ch on ch.character_id = a.character_id
GROUP BY a.character_id
LIMIT 20
"""
print("Character ID, character name, number of items")
curs.execute(query10).fetchall()

#How many weapons each character has?
#left join statement should come after FROM statement followed by WHERE, GROUP BY, etc.
query11= """
SELECT a.character_id, d.name, count(a.item_id) 
FROM charactercreator_character_inventory as a, armory_item as b, armory_weapon as c 
left join charactercreator_character as d on d.character_id = a.character_id
WHERE a.item_id = b.item_id AND b.item_id = c.item_ptr_id
GROUP BY a.character_id 
LIMIT 20
"""
print("Character ID, Chacter name, number of weapons")
curs.execute(query11).fetchall()

#On average, how many items each Character has?
query12="""
SELECT COUNT(inventory.item_id) * 1.0/ COUNT(DISTINCT inventory.character_id)
FROM charactercreator_character_inventory AS inventory
"""
results6 = curs.execute(query12).fetchall()

print("Average number of items per character=", results6)

#On average how many weapons each character has?
query13="""
SELECT COUNT(a.item_id) *1.0 / COUNT(DISTINCT a.character_id)
FROM charactercreator_character_inventory AS a, armory_weapon AS b
WHERE a.item_id = b.item_ptr_id
"""
results7 = curs.execute(query13).fetchall()

print("Average number of weapons per character=", results7)